### PR TITLE
Fix byte strings

### PR DESCRIPTION
**Pull request by Geoff99**
Hi @jbuehl 
This pull request contains 3 small fixes motivated to the conversion from Python 2 to 3.x.

The first fixes the "trap", in **se/datadevices.py**, which detects and corrects Nan values which the solaredge inverter 0x0022 message incorrectly transmits in big endian rather than little endian order (relevant to the `PfromX` values).

The second implements a similar correction, in **se/data.py** for a similar issue with the `Pmax` value decoded by the inverter device.

The third, in **se/datadevices.py**, changes the `battery ID`, deciphered from the 0x0030 message type, from byte string to unicode string. This is necessary since the `battery ID` is later used as a dictionary key, and Python 3.x raises exceptions when the key is a byte string.

Regards
Geoff

### CODE REVIEW

**Comment by Geoff99** [comment]
Hi @ericbuehl 
Not easily (I don't see Nan values often in my datastream these days) .  The Nan values for both `Pmax` and `PfromX` were appearing in the values being reported by @DatafoxChris here https://github.com/jbuehl/solaredge/issues/136#issuecomment-514519785
so one of his pcap files may test the first 2 fixes.

I can supply a pcap file containing battery data, which would test the third fix (see attached).  (It also tests that changes 1 and 2 don't break anything (obvious) when the value is **not** Nan).

[190801.1135.test.pcap.zip](https://github.com/jbuehl/solaredge/files/3455098/190801.1135.test.pcap.zip)

Without the third fix, the `json.dumps` call in the following step fails silently , whenever a battery_0x0030 message occurs. (ie the only sign of the error is the **absence** of some output json from inverters and optimizers that should otherwise be there)

https://github.com/jbuehl/solaredge/blob/71e10e5fbb2c5ef485b36bb13502e947bbbf1c74/se/data.py#L246-L255

----------------------------------------------

By the way, the following error message which also appears in the issue #136
```
Failed to parse message: Unknown format code 'x' for object of type 'str'
data: 42 00 bd ff 8b 02 96 3d 12 73 fe ff ff ff 00 05
...
```
seems to be related to related to byte versus Unicode strings, ie Python 2 versus 3 behaviours.  It is emitted from

https://github.com/jbuehl/solaredge/blob/129b93101e1e45d57e6a40661791cab99d53bbcc/semonitor.py#L66-L67

and appears to be caused by the `x.encode('hex')` part of the following code

https://github.com/jbuehl/solaredge/blob/71e10e5fbb2c5ef485b36bb13502e947bbbf1c74/se/data.py#L52-L54 

but I haven't managed to figure out why yet :-(  My reading of the documentation says it should be legitimate for the version of Python I am using.

**Comment by Geoff99** [comment]
Apologies @ericbuehl 
I *knew* I'd checked the Nan values somehow.  The pcap file I provided in the previous comment https://github.com/jbuehl/solaredge/pull/138#issuecomment-517138083 includes both Nan and real values for the meters_0x0022 fields `PfromX` and `P2X`, so can be used to stress test the first change.
Only Nan values for the the inverter's `Pmax` are not present, so only the 2nd fix is not tested by the pcap file.

**Comment by ericbuehl** [comment]
Awesome — can you add the test file to the test directory along with the expected output so this gets covered by the automated tests?

**Comment by Geoff99** [comment]
Hi @ericbuehl, @jbuehl 
I **think** I have discovered a (probably not very important) problem with the conversion to Python3.x.
It only appears (on my hardware and use case) when running semonitor with the `-v` (or stronger) argument. It can be observed in the pcap file I attached earlier in this thread.

My inverter occasionally emits a unknown function code of `0x03c2` which results in
```
Unknown function 0x03c2
Failed to parse message: 'int' object has no attribute 'encode'
``` 

It is related to this line of code
https://github.com/jbuehl/solaredge/blob/71e10e5fbb2c5ef485b36bb13502e947bbbf1c74/se/data.py#L54
which is executed if the `parseData` code encounters an unknown function. 

The problem is that `data` is a byte string.  As I have just learnt, iterating over a byte string yields an integer value, and integers do not have an encode method, so the `x.encode('hex')` expression raises an exception, which is later trapped and reported upon in the `Failed to parse` message I am seeing.  It has no substantive effect (since the action anyway is simply to ignore the message with the unknown function). It can be fixed (in Python 3.x, where x is sufficiently large, I am testing using 3.7) by changing the line to `return data.hex()`.  But this makes Python2.7 unhappy :-(  

Not really sure what (if anything) to do - amongst other things I am only just now starting to *learn* Python3.x -  so advice would be appreciated.

Although this issue has no substantive effect here (so do nothing is a viable option) I have noticed that the same idiom `x.encode('hex') for x in <somebytestring>` appears elsewhere in the semonitor code.  It is not in parts of the code that are exercised by my hardware (for eg my inverter doesn't encrypt it's transmissions, and I only listen passively to the data stream), but the underlying issue *may* have more impact on other users.

PS If it would be more appropriate / useful to open a separate issue instead of including this in the comments on the current pull request, just say.  I put it here because I came across it in the course of debugging and testing the current pull request which is related to how Python 3.x treats byte strings.

**Comment by Geoff99** [comment]
Hi @ericbuehl ,
I must have been typing my previous comment while you were posting yours. (so the thread sequence looks a bit disjointed)
Confession time : I don't really understand the Python testing framework (yet).  I'll have a look at what's involved in adding the test file and the expected output, and see what I can learn, but I may be a bit slow, and need a bit of guidance if I get stuck.

**Comment by ericbuehl** [comment]
@Geoff99 no worries! If you drop your pcap in the appropriate folder within the test directory and then run test

**Comment by ericbuehl** [comment]
(Sorry I fat fingered the PR close and early comment submission on mobile)

**Comment by Geoff99** [comment]
Hi @ericbuehl 
Mmm, this is turning into an education for me = worthwhile and fun

Progress, of sorts.

* setting up the tests seems quite straightforward, *except* that
* I usually work in a Windows environment, so bash scripts don't work too well :-( *but*
* I did create the  `.json` output file locally on my Windows machine, and put the pcap and json files into the appropriate places and pushed them to my GitHub pull request branch (whilst crossing fingers that the magic of git will sort out any Window CRLF versus Linux LF line ending issues with the json file), *but*
* the pull request was failed by the CircleCI tests, because of the exception that `parseData` generates when returning from an 'unknown function' situation (see explanation here https://github.com/jbuehl/solaredge/pull/138#issuecomment-517525992) , *however*
* some internet searching uncovered a solution to the `parseData` return value issue (which on my local machine seems to work for both Python2.7 and Python3.7), so I pushed that additional fix to the GitHub pull request, and *now*
* the CircleCI tests seems to execute semonitor OK, *but*
* detect that my "correct" json file (generated on my local Windows machine) is different to the ones generated by `test/test.sh` under both Python2 and Python3 :-(

I'm still investigating why - although at **first** glance at the CircleCI results, it appears that the `test/test.sh` version of the json file is missing a few of the messages I am seeing in my Windows generated version.  I have yet to confirm that though, and still haven't got as far as debugging *why* that might be happening.

I may have to set up a local Linux environment where I can step through/debug what is happening when `test/test.sh` runs more easily.

Anyway, I'll keep you posted as I discover/learn more.

**Comment by ericbuehl** [comment]
It looks like one thing that is tripping up the diff is a possible difference in time zone.  All the times are mismatched by exactly 7 hours.  I believe circle is running in UTC

eg `"Time": [-"11:39:47",-] {+"18:39:47",+}`

**Comment by Geoff99** [comment]
Thanks @ericbuehl , that's very helpful indeed.  

I was mis-reading the CircleCI diff output when I thought some messages were missing - my mistake.

Looking at the output now I can see that the json file I supplied uses my local time zone (UTC + 10), while the `test/test.sh` that CircleCI runs is generating a json file using the US/Pacific timezone (currently UTC - 7), so the `Date` and `Time` fields in my json file are one day ahead and 7 hours behind (ie ("+10" - "-7") = 17 = (+24 - 7) hours ) the ones generated by the CircleCI.

I'll look into how I might generate a json file in the time zone the tests expect - I suspect that will be simpler than trying to tell the tests to use *my* timezone, just for *my* pcap file :-)

**Comment by Geoff99** [comment]
Hi @ericbuehl 

Success :-) 

Albeit after a fair bit of (very useful) education for me.

I was able to generate a correct time zone json file on my Windows machine, by adjusting the pc time zone before running semonitor.

However I had less luck creating  an acceptable .rec file from semonitor (haven't figured out why though), so ended up setting up Ubuntu as dual boot on my pc (has been on my to do list for a while), installing assorted software, and actually running test/test.sh there.

Took a while because I didn't know anything about git-lfs (the way git copes with large binary files), since it was installed automatically for me when I installed git-for-Windows.  The consequence was that tshark under my Ubuntu clone of the solaredge repo complained about pcap files not being in pcap format -  quite reasonably it turned out, since they were just text stubs pointing to the git-lfs store where the real pcap files were.  After much looking in the wrong place (tshark issues), I eventually learnt about git-lfs, installed it on my Ubuntu system, and with a bit of messing around, managed to create the .rec and .csv files the CircleCI tests were expecting to see.

There **is** one outstanding issue to be considered before closing this pull request, namely the other places in the code where the `''.join(x.encode('hex') for x in <somebytestring>)` occurs, as mentioned here https://github.com/jbuehl/solaredge/pull/138#issuecomment-517525992.  Thus far I have only altered the single case that was causing my specific pcap test data to fail.  I'm reasonably sure that the other instances would also raise exceptions; also that the same fix I applied here would resolve them.  But they occur in sections  of the code not exercised by my hardware / use case.  Would you like me to also change them - or just leave them alone?

PS If it helps, I can list them out for you.

**Comment by ericbuehl** [comment]
Hi @Geoff99 congrats on getting your tests working and congrats on escaping your windows boot :) I remembered that the time zone was specifically being set by the test cases here: https://github.com/jbuehl/solaredge/blob/master/test/test.sh#L6  However you seem to have gotten past that hurdle.  Let's merge this PR!

While you're probably right that the other instances of hex encoding you found would likely break, let's hold off on blinding replacing that code until we have an example that exercises it.  It's entirely likely that there are other incompatible code paths that would need to be updated in tandem.  The hex encoding instances you found can be updated then.

**Comment by Geoff99** [comment]
Thanks for your help and guidance @ericbuehl, glad to have been able to make a (very tiny) contribution to this great project.

I learnt some useful stuff and it was fun, and I finally got an Ubuntu boot setup on my desktop as well (I have had Linux on my Raspberry Pi's for a while now), so valuable for me in several ways :-) .

I agree **completely** with not making changes that can't be tested - **way too easy** to mess up!

For future reference, in summary the problem with  

```
''.join(x.encode('hex') for x in <somebytestring>')
```

is that the iterator over `<somebytestring>` yields a value `x` that is an **integer** (no idea why!), hence does not have an `encode` methods, and so raises an exception.

The (*a*) solution I found is to replace the phrase with
```
import codecs
. . . 
codecs.encode(<somebytestring>, 'hex').decode('ascii')
```

`codec.encode` returns **another** bytestring containing a hex representation of `<somebytestring>` ; the `.decode('ascii')` converts this to a *proper* (unicode style) string.

**Comment by Jerrythafast** [comment]
@Geoff99, I was triggered by 'no idea why' as it's pretty obvious if you realise what a `bytes` object really is: it's a sequence of bytes, and bytes are merely numbers (between and including 0 and 255). So iterating over a sequence of numbers gives you numbers ;)

**Comment by Geoff99** [comment]
Thanks @Jerrythafast ,
I am *just* now converting to Python3 (my tardiness a combination of laziness, reliance on some older packages that themselves took a while to be converted to Python3, and lacking a trigger - until recently when my hardware gave up the struggle and I had to set up a new pc anyway).

I must say, now I am getting my mind around the changes, they do indeed make a lot of sense, with the bytes versus **every** string is really a sequence of Unicode code points difference being a major clarification for me - I never really understood encodings before, probably because I (ignorantly) tended to lump Unicode itself in there as *just* another encoding, so I could never figure out the logic of which way was `encode`, and which way was `decode` - they were both just transforms from one representational convention to another.

Prompted by your (gentle and polite) prod, I have just re-read the Python Unicode HOWTO, and the logic is becoming much clearer to me now, so perhaps I should update my comment to "I now have some idea why" :-).  

I'm still a *tiny* bit puzzled as to why iterating over a bytes object (a sequence of bytes) yields something that is **typed** as an `int`, rather than **typed** as a `bytes` (with only a single byte in it, hence could be interpreted as an integer number between 0 and 255 inclusive).  But I absolutely agree, logically it cannot possibly be of type `str`.  

I may be missing some subtleties in the distinction between a *sequence* of `somethings`, and an *individual instance* of a `something`.  So maybe I need to read a bit more about the distinction between `bytes` and `bytearrays`. Or maybe just read the Unicode HOWTO a couple more times.

Anyway, the real fun for me is learning (and making sense of) new stuff so this has been quite a valuable exercise - especially since it began with a pull request to change a single character of code, from `'\xff\xff\x7f\xff'` to `'b\xff\xff\x7f\xff'` :-) :-)  

Like I said, thanks all for helping with my education, always appreciated.

**Pull request merged**
